### ISSUE TITLE
Auto-update feature causes error message

### ISSUE THREAD

**Issue by wcxu21** [Leo-Corporation/ColorPicker#110]
### Enhancement

By default, the software enables the option to automatically check for updates at startup. This option will pop up an error message at startup for some users who cannot access the Github service.

Some networks in China may not be able to access Github or access is very slow, which will cause errors at startup.

It is recommended that you uncheck the check at startup, and let users choose the check for updates function themselves.

Thanks for your work.

**Comment by Leo-Peyronnet** [comment]
I will add in a future update a message box on startup that will ask the user if they want to have automatic updates turned on. I'm also going to implement this feature across other softwares.
