### ISSUE TITLE
[Bug] Complain about missing .NET; But .NET is already installed

### ISSUE THREAD

**Issue by pstein** [Leo-Corporation/ColorPicker#157]
### What is the bug?

I installed v4.3.0 on 64bit Win10.
When I start ColorPicker an error popup appears:

"To run this application, you must install missing framework for .NET.
Would you download it now?"

BUT: I have already installed 64bit .NET Runtime v6.0.6!
What more can I do?

The error popup should tell the user which .NET Runtime is missing

### How to reproduce the bug?

see above

### Operating System

Windows 10

### What is the version of the operating system?

21H2

### What is the version of the software?

4.3.0

**Comment by Leo-Peyronnet** [comment]
Make sure that you have installed the .NET **DESKTOP** Runtime, not the runtime alone. If you didn't have any .NET runtimes installed, the error message would show which runtime, and which version you'll need to install. Microsoft .NET generates this message, and I can't modify it.

You can check if you have the desktop runtime installed by running `dotnet --info` in a command prompt.
If you have the **DESKTOP** runtime installed, you should see `Microsoft.WindowsDesktop.App 6.0.6` in ".NET runtimes installed:"
If you only have installed the runtime, you only should see `Microsoft.NETCore.App 6.0.6`.

You can download the desktop runtime here: [https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer)
