### ISSUE TITLE
[Misc] How to pick a color?

### ISSUE THREAD

**Issue by FabianLoRs** [Leo-Corporation/ColorPicker#264]
### Description of your issue

Hello Leo, how to pick a color? i can't:

![Animation_02](https://user-images.githubusercontent.com/122753033/230958251-5f98d77c-9ecc-42c8-98de-babba9f85926.gif)

Cheers.

**Comment by Leo-Peyronnet** [comment]
You can hit Shift+S to start/stop the selection. Shift+C to copy the color.

**Comment by FabianLoRs** [comment]
How to copy the hex code?

**Comment by Leo-Peyronnet** [comment]
You can go in Picker > Selector and then click on the copy button next to the HEX Value.
![image](https://user-images.githubusercontent.com/55453279/231228776-469c3486-0c9a-4fa3-bf89-dd52802e779b.png)

If you'd like to always copy the HEX code, you can go in Settings > Color Options > Default color type
![image](https://user-images.githubusercontent.com/55453279/231228907-7cb154dd-49fd-4740-8219-84d973c21317.png)
