### ISSUE TITLE
Can you provide a portable version?

### ISSUE THREAD

**Issue by pstein** [Leo-Corporation/ColorPicker#344]
### Enhancement

Can you provide a portable version of ColorPicker?

**Comment by Leo-Peyronnet** [comment]
Working on it!

**Comment by Leo-Peyronnet** [comment]
Portable mode is now available in the [latest release.](https://github.com/Leo-Corporation/ColorPicker/releases/tag/5.7.1.2311) Please note that some features, such as automatic updates are not available in portable mode.

Thank you for your suggestion.
