### ISSUE TITLE
[Bug] Changing a theme will close the program

### ISSUE THREAD

**Issue by vavavr00m** [Leo-Corporation/ColorPicker#392]
### What is the bug?

Changing a theme will exit the program without any error.

### How to reproduce the bug?

Select any other theme than your current.

### Operating System

Windows 10

### What is the version of the operating system?

Version 22H2 (OS Build 19045.4046)

### What is the version of the software?

v6.0.0.2402

**Comment by Leo-Peyronnet** [comment]
Hi,
Thanks for reporting this issue. I investigated and found a fix that will soon be included in the next release.
